### ISSUE TITLE
Issue with Mobile Image in Mozilla Firefox.

### ISSUE THREAD

**Issue by faizan-glitch** [Rumman-Fahim/Giraffe.github.io#1]
The mobile image on the homepage does not appear on Mozilla Firefox. It works on Chromium based browser though. Add support for Firefox too.
Firefox
![image](https://user-images.githubusercontent.com/58991337/90317777-179b1b80-df45-11ea-8bfc-c8990a11322f.png)

Chromium-based:
![image](https://user-images.githubusercontent.com/58991337/90317788-27b2fb00-df45-11ea-8127-bb5f2d6f49d2.png)

**Comment by Rumman-Fahim** [comment]
Thank you
I will fix this issue.
